### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by JuhQ** [kanbahn/kanbahn.github.io#21]
Huomioita käytettävyydestä
  - Google login, nice!
  - Kortteja ei vissiin voi sortata tällä hetkellä?
  - Olisi kiva jos korttien väriä voisi muuttaa, esimerkiksi prioriteetin mukaan
  - Olisi myös kiva jos olisi jaettavia urleja, jotta voin vaikka tiimilleni jakaa jonkun boardin, johon kaikki voi lisäillä asioita
  - Poistoissa olisi hyvä olla varmistus
  - Kortteja voi siirtää lanelta toiselle, olisi myös kiva jos muitakin elementtejä voisi siirrellä?
    - Esim olisi kiva jos voisin nostaa jonkin boardin ylimmäksi tai muuttaa lanien järjestystä
  - Nyt voin luoda loputtomasti tyhjiä kortteja, onko tämä tarkoituksella?
    - Tulisiko uuden kortin voida luoda vasta kun aikaisempaan on lisätty sisältöä?
  - Responsiivisuus! Erittäin hyvä, tätähän voi käyttää mobiililla :)

Backend
  - typescript! Nice
  - Koodi on tosi selkeää ja hyvin kirjoitettua
  - Ensimmäinen projekti jossa nään migraatioskriptejä, tosi jees
  - Olisi ollut tosi kiva nähdä backendille testejä

Frontend
 - App.tsx tiedostossa on määritelty myös LoginButton komponentti, tämä olisi hyvä olla omana tiedostonaan components hakemistossa
 - html tageissa on hyvä määritellä merkkijonot tuplahipsuina, eli
  ```
  <TextArea
    value={task.title}
    onChange={handleChange}
    wrap='soft'
    minRows={2}
  />
  ```
  muotoon
  ```
  <TextArea
    value={task.title}
    onChange={handleChange}
    wrap="soft"
    minRows={2}
  />
  ```
    - tällä tosin ei ole paljoakaan merkitystä, lähinnä käytäntöä
  - importtien järjestyksessä kannattaa pitää mielessä nyrkkisääntöä: ensin npm moduulit, sitten omat komponentit, sitten css
  ```
  import React from 'react'
  import FeatureLane from './FeatureLane'
  import { connect } from 'react-redux'
  import { Task } from '../../src-common/entity/Task'
  import { List } from '../../src-common/entity/List'
  import { StoreState } from '../store/store'
  import { unique } from '../helpers'
  import styled from 'styled-components'
  import { GradientContainer, transparentButtonStyles } from './common'
  import { addList } from '../store/listReducer'
  import { Plus } from 'react-feather'
  ```
  muotoon

  ```
  import React from 'react'
  import { connect } from 'react-redux'
  import styled from 'styled-components'
  import { Plus } from 'react-feather'
  import FeatureLane from './FeatureLane'
  import { Task } from '../../src-common/entity/Task'
  import { List } from '../../src-common/entity/List'
  import { StoreState } from '../store/store'
  import { unique } from '../helpers'
  import { GradientContainer, transparentButtonStyles } from './common'
  import { addList } from '../store/listReducer'
  ```
  - itse käytän visual studio codessa `sort-imports` nimistä laajennusta joka hoitaa tämän puolestani
    - se sorttaa komponentit myös tietyllä logiikalla, jätän tämän selvittämisen sinulle ;)

Kaiken kaikkiaan tosi hyvänlaatuista koodia, moitittavaa ei löytynyt! :)
Tästä on hyvä jatkaa

**Comment by juhapekkamoilanen** [comment]
Kiitos Juha, tosi hyvää palautetta!

Moni mainitsemasi feature olikin jo mielessä, mutta hyviä uusia ideoita myös :)

Ja noi pienet tyyli/käytäntövinkit on tosi arvokkaita! Niitä ei välttämättä aina niin huomaa.
